export enum IssueActionType {
  UPDATE_ISSUE = 'UPDATE_ISSUE',
  ADD_EDIT_ISSUE = 'ADD_EDIT_ISSUE',
  EDIT_ISSUE_TRUE = 'EDIT_ISSUE_TRUE',
  EDIT_ISSUE_FALSE = 'EDIT_ISSUE_FALSE',
  NEXT_ISSUE = 'NEXT-ISSUE',
  PREV_ISSUE = 'PREV-ISSUE',
}
